### ISSUE TITLE
It doesn't handle unsigned integer properly

### ISSUE THREAD

**Issue by liangde-chen** [valery1707/kaitai-gradle-plugin#17]
I have some kaitai file like this: 
```
types:
  setting_t:
    seq:
    - id: profile_id
      type: u4
      enum: profile_ids
enums:
  profile_ids:
    0x00000003: defaults                # Known default value is used.
    0xFFFFFFFF: not_found               # Value not found.
```

And the generated java code failed to be compiled: 
`NOT_FOUND(4294967295);`
Error: integer number too large.
